myName = input("What's your name?")
myFood = input("What's your favourite food?")
myMusic = input("What music do you currently vibe strongly to?")
myAddress = input("Where do you live?")
print()
print("Wow!")
print(myName)
print("Nice to meet you!")
print()
print("I also love eating")
print(myFood)
print()
print("And listening to")
print(myMusic)
print()
print(myAddress)
print("Is a good place to live.")
print()
print()
print("I want to tell you that you rock, and that you're making giant strides in your career.")
